FROM maven:3.5.4-jdk-8-alpine as maven
COPY ./pom.xml ./pom.xml
COPY ./src ./src
#run dependencies from pom.xml
RUN mvn dependency:go-offline -B
# Build the application
RUN mvn package
FROM openjdk:8u171-jre-alpine
WORKDIR /adevguide
COPY --from=maven target/SimpleJavaProject-*.jar ./adevguide/SimpleJavaProject.jar
CMD ["java", "-jar", "./adevguide/SimpleJavaProject.jar"]
